version: '3'
services:
  deepstream:
    # 3.1.0 (latest), v4.0.0-rc.2-alpine (NOTE: v4 login not working)
    image: deepstreamio/deepstream.io:3.1.0
    ports:
      - "6020:6020"
      - "8080:8080"
    # volumes:
    #   - ./deepstream/conf:/opt/deepstream/conf
    #command: ./deepstream start --disable-auth --disable-permissions

  dotnet:
    build:
      context: ./dotnet
      args:
        http_proxy: ${http_proxy}
        https_proxy: ${http_proxy}
        no_proxy: ${no_proxy}
    environment:
      DEEPSTREAM_URL: deepstream:6020
      DEEPSTREAM_USER: ${DEEPSTREAM_USER}
      DEEPSTREAM_PWD: ${DEEPSTREAM_PWD}
      DEEPSTREAM_EVENT: test
    depends_on:
      - deepstream

  java:
    build:
      context: ./java
      args:
        http_proxy: ${http_proxy}
        https_proxy: ${http_proxy}
        no_proxy: ${no_proxy}
        JAVA_OPTS: ${JAVA_OPTS}
    environment:
      DEEPSTREAM_URL: deepstream:6020
      DEEPSTREAM_USER: ${DEEPSTREAM_USER}
      DEEPSTREAM_PWD: ${DEEPSTREAM_PWD}
      DEEPSTREAM_EVENT: test
    depends_on:
      - deepstream
